const PDFDocument = require('pdfkit');

/**
 * Generate a Mirifer Report PDF
 * @param {Array} entries - Array of 14 day entries with day, title, question, user_text, ai_text, created_at
 * @param {Object} userInfo - User information (access code, etc.)
 * @returns {PDFDocument} - PDF stream
 */
function generateMiriferReport(entries, userInfo) {
    const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 50, bottom: 50, left: 50, right: 50 }
    });

    // Sort entries by day
    const sortedEntries = entries.sort((a, b) => a.day - b.day);
    const firstDay = sortedEntries[0];
    const lastDay = sortedEntries[sortedEntries.length - 1];

    // Cover Page
    generateCoverPage(doc, firstDay.created_at, lastDay.created_at);
    doc.addPage();

    // Journey Summary
    const synthesis = lastDay.mode === 'synthesis' && lastDay.ai_text
        ? lastDay.ai_text
        : generateDefaultSynthesis(sortedEntries);
    generateJourneySummary(doc, synthesis);
    doc.addPage();

    // Daily Pages
    sortedEntries.forEach((entry, index) => {
        generateDayPage(doc, entry);
        if (index < sortedEntries.length - 1) {
            doc.addPage();
        }
    });

    // Add footer to all pages
    addFooters(doc);

    doc.end();
    return doc;
}

function generateCoverPage(doc, startDate, endDate) {
    const startFormatted = new Date(startDate).toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric'
    });
    const endFormatted = new Date(endDate).toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric'
    });

    doc.fontSize(32)
        .font('Helvetica-Bold')
        .text('Mirifer Report', { align: 'center' })
        .moveDown(1);

    doc.fontSize(16)
        .font('Helvetica')
        .text('Uncertainty Reduction System — Personal Summary', { align: 'center' })
        .moveDown(2);

    doc.fontSize(12)
        .text(`Journey Period: ${startFormatted} to ${endFormatted}`, { align: 'center' })
        .moveDown(4);

    doc.fontSize(10)
        .font('Helvetica-Oblique')
        .text('This is not medical or mental health advice.', { align: 'center' })
        .moveDown(0.5)
        .text('This report is a neutral summary of your reflections during the 14-day Mirifer process.', { align: 'center' });
}

function generateJourneySummary(doc, synthesis) {
    doc.fontSize(20)
        .font('Helvetica-Bold')
        .text('Journey Summary', { align: 'left' })
        .moveDown(1);

    doc.fontSize(11)
        .font('Helvetica')
        .text(synthesis, { align: 'left', lineGap: 4 });
}

function generateDayPage(doc, entry) {
    // Header
    doc.fontSize(18)
        .font('Helvetica-Bold')
        .text(`Day ${entry.day} — ${entry.title}`, { align: 'left' })
        .moveDown(1);

    // Question
    doc.fontSize(12)
        .font('Helvetica-Bold')
        .text('Question:', { continued: false })
        .moveDown(0.3);

    doc.fontSize(11)
        .font('Helvetica')
        .text(entry.question, { align: 'left', lineGap: 3 })
        .moveDown(1);

    // User Reflection
    doc.fontSize(12)
        .font('Helvetica-Bold')
        .text('Your Reflection:', { continued: false })
        .moveDown(0.3);

    doc.fontSize(11)
        .font('Helvetica')
        .text(entry.user_text || '[No reflection recorded]', { align: 'left', lineGap: 3 })
        .moveDown(1);

    // Mirifer Reflection
    doc.fontSize(12)
        .font('Helvetica-Bold')
        .text('Mirifer Reflection:', { continued: false })
        .moveDown(0.3);

    doc.fontSize(11)
        .font('Helvetica')
        .text(entry.ai_text || '[No reflection generated]', { align: 'left', lineGap: 3 });
}

function generateDefaultSynthesis(entries) {
    // Fallback synthesis if Day 14 doesn't have one
    return `This 14-day journey explored patterns of uncertainty and constraint. The reflections reveal recurring themes in how you navigate decision-making and ambiguity. This summary is a neutral observation of your documented process. Today is complete.`;
}

function addFooters(doc) {
    const pages = doc.bufferedPageRange();
    const generatedDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric'
    });

    for (let i = 0; i < pages.count; i++) {
        doc.switchToPage(i);
        doc.fontSize(9)
            .font('Helvetica')
            .text(
                `Generated by Mirifer — ${generatedDate}`,
                50,
                doc.page.height - 30,
                { align: 'center' }
            );
    }
}

module.exports = { generateMiriferReport };
